# Generated by Django 5.2.17 on 2026-09-21 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('email_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('email_otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('phone_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('phone_otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('two_factor_enabled', models.BooleanField(default=True)),
                ('two_factor_method', models.CharField(choices=[('authenticator', 'Authenticator App'), ('email', 'Email OTP'), ('phone', 'Phone OTP'), ('recovery_code', 'Recovery Code')], default='email', max_length=20)),
                ('totp_secret', models.CharField(blank=True, max_length=64)),
                ('recovery_codes', models.JSONField(blank=True, default=list)),
                ('two_factor_temp_token', models.CharField(blank=True, max_length=128, null=True)),
                ('two_factor_temp_created_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('password_reset_otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=128, null=True)),
                ('password_reset_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
