# Generated by Django 5.2.17 on 2026-08-27 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('rooms', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GENERATED', 'Allocation Generated'), ('REGENERATED', 'Allocation Regenerated'), ('MOVED', 'Student Moved'), ('SWAPPED', 'Students Swapped'), ('ROOM_CHANGED', 'Room Changed'), ('SEAT_CHANGED', 'Seat Changed'), ('LOCKED', 'Session Locked'), ('UNLOCKED', 'Session Unlocked'), ('EXCLUDED', 'Student Excluded'), ('ADDED', 'Student Added'), ('EXPORTED', 'Report Exported')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='examinations.examsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False, help_text='True if this allocation was manually assigned or adjusted')),
                ('substituted_branch', models.CharField(blank=True, help_text='Original expected branch if substitution occurred', max_length=10)),
                ('substitution_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='students.examcandidate')),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='examinations.examsession')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='rooms.room')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='rooms.seat')),
            ],
            options={
                'ordering': ['room__room_number', 'seat__seat_number'],
                'unique_together': {('exam_session', 'candidate'), ('exam_session', 'room', 'seat')},
            },
        ),
    ]
