# Generated by Django 5.2.17 on 2026-08-27 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(default=42)),
                ('columns', models.PositiveIntegerField(default=3)),
                ('rows', models.PositiveIntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('row', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='rooms.room')),
            ],
            options={
                'ordering': ['seat_number'],
                'unique_together': {('room', 'seat_number')},
            },
        ),
    ]
