# Generated by Django 5.2.17 on 2026-08-27 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NRUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='nr_uploads/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Validated'), ('ERRORS', 'Has Errors'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], default='UPLOADED', max_length=15)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nr_uploads', to='examinations.examsession')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NR Upload',
                'verbose_name_plural': 'NR Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NRValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('error_type', models.CharField(choices=[('MISSING_PIN', 'Missing PIN'), ('DUPLICATE_PIN', 'Duplicate PIN'), ('MISSING_NAME', 'Missing Name'), ('INVALID_BRANCH', 'Invalid Branch'), ('INVALID_YEAR', 'Invalid Year'), ('INVALID_CURRICULUM', 'Invalid Curriculum'), ('MISSING_SUBJECT_CODE', 'Missing Subject Code'), ('MISSING_SUBJECT_NAME', 'Missing Subject Name'), ('INVALID_CATEGORY', 'Invalid Category'), ('DUPLICATE_RECORD', 'Duplicate Record'), ('INVALID_DATA', 'Invalid Data')], max_length=25)),
                ('column_name', models.CharField(blank=True, max_length=50)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('nr_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='nr_import.nrupload')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
